# Generated by Django 6.0.3 on 2026-05-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
