# Generated by Django 6.0.3 on 2026-04-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(choices=[('cuisinier', 'Cuisinier'), ('serveur', 'Serveur'), ('caissier', 'Caissier'), ('manager', 'Manager')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('date_embauche', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
